export interface AnalysisResult {
  species: string;
  scientificName: string;
  confidence: number;
  description: string;
  habitat: string;
}

export interface Photo {
  id: string;
  url: string; // Base64 or Blob URL
  timestamp: number;
  analysis: AnalysisResult;
  funCaption?: string; // Generated by Flash-Lite
}

export interface Album {
  id: string;
  name: string; // Species name
  coverPhotoUrl: string;
  photos: Photo[];
  wikiSummary?: string; // Fetched via Search Grounding
  wikiUrl?: string;
}

export interface AppState {
  albums: Record<string, Album>; // Keyed by species name (lowercase normalized)
  recentPhotos: Photo[];
}